Make scripts easier-to-read.
Add a lot more comments.
Refactor to group actions into functions.
Simplify git-scratch by removing unused generalizations (extra elbows).

diff --git a/git-addfile b/git-addfile
--- a/git-addfile
+++ b/git-addfile
@@ -1,31 +1,76 @@
 #!/bin/bash -eu
 
-getopts t: opt && shift $(( OPTIND -1 ))
+die() { echo "$*"; exit 1; } >&2
 
-git rev-parse --git-dir &> /dev/null
-if [[ $# -eq 0 ]]; then
-  echo 'echo hello, world' > hello
-  chmod +x hello
-  diff - <(./hello) <<< "hello, world"
-  git add .
-  git commit -m"the canonical program"
-else
-  for i in "$@"; do
-    [ ${i:0:1} != '/' ] # relative paths & real files only
-    name="$PWD/$i"
-    rm -rf $name
-    if [[ ${name: -1:1} = '/' ]]; then
-      install -d $name
-      > $name/.gitkeep
-    else
-      install -d $(dirname $name)
-      echo "file $i" > $name
+parse-args() {
+    # Process optional args
+    #
+    # -h: help
+    # -t tagname: name to tag the commit
+	# bash lacks good arg parsing
+    usage="git addfile [-t tagname | -h] [file-or-dir ...]"
+    while getopts ":ht:" opt; do
+        case $opt in          
+            h) echo "usage: $usage" ; exit 0 ;;
+            t) tag=$OPTARG; shift 2;;
+            \?) echo "Invalid option: -$OPTARG" >&2; die "$usage" ;;
+            :) die "Option -$OPTARG requires an argument." >&2 ;;
+        esac
+    done
+}
+
+add-and-commit() {
+    # Add and commit everything new or changed in this directory
+    #
+    # Normally, these are separate steps,
+    # here, we're just cramming stuff in.
+    git add .                   # add everything
+    git commit -m"$@"           # commit it
+    if [[ "${tag:-}" ]]; then   # tag if requested
+      git tag $tag
     fi
-    git add .
-  done
-  comment="add file(s) $@"
-  git commit -m"$comment"
+}
+
+sanity-checks() {
+    # Does it make sense to run this script?
+    git rev-parse --git-dir &> /dev/null # in a git repo?
+}
+
+add-canonical-program() {
+    # The classic, hello, world as a shell script
+    echo 'echo hello, world' > hello        # create the program
+    chmod +x hello                          # make it executable
+    diff - <(./hello) <<< "hello, world"    # test it
+    add-and-commit "the canonical program"  # commit it
+    git add .                               # add it
+    git commit -m"the canonical program"    # commit it
+}
+
+create-file-or-directory() {
+    # Create a named file
+    [ ${name:0:1} == '/' ] &&                    # first character is a '/'? (`addfile /foo`)
+        die "relative paths only"                # only allow relative paths
+    name="$PWD/$name"                            # convert to absolute paths
+    [-e "$name"] && die "$name already exists"   # tread not on what's there
+    if [[ ${name: -1:1} = '/' ]]; then           # last character is a '/'? (`addfile foo/`)
+      install -d $name                           # add empty directory
+      > $name/.gitkeep                           # empty hidden file because
+                                                 # git ignores empty dirs
+    else                                         # `addfile foo/bar`
+      install -d $(dirname $name)                # create file in directory
+      echo "entry $name" > $name                 # real contents
+    fi
+}
+
+sanity-checks
+parse-args "$@"
+
+if [[ $# -eq 0 ]]; then
+    add-canonical-program    # we're done!
+    exit 0              
 fi
-if [[ "${OPTARG:-}" ]]; then
-  git tag $OPTARG
-fi
+
+for name in "$@"; do    # create each name on command line
+    create-file-or-directory $name
+done
+add-and-commit "add elements(s) $@"            # add & commit all
diff --git a/git-scratch b/git-scratch
--- a/git-scratch
+++ b/git-scratch
@@ -1,91 +1,144 @@
 #!/bin/bash -eu
-# create a scratch repo for experiments
 
-# checkout a branch,
-# make an easy-to-follow change
-checkout-and-mark() {
-  git checkout $1
-  echo "From branch $1" > README.$1      # make a change that lets you see what branch it's in
-  [ "$conflict" ] && mv README.$1 README # make all changes to the same file
-  git add .
-  git commit -m"commit in branch $1"     # use a commit message that names the branch, too
+# pick one of these two
+TMPDIR=/tmp               # if you want everything in /tmp
+TMPDIR=$PWD               # if you want everything right here
+
+SCRATCH=$TMPDIR/scratch   # the basic repo
+REMOTE_REPOS_DIRECTORY=$TMPDIR/remote_repos # on your far-away, Git server, "localhost"
+ITCHY=$TMPDIR/itchy       # a local clone, by Itchy Mouse
+SCRATCHY=$TMPDIR/scratchy # a local clone, by Scratchy Cat
+
+die() { echo "$*"; exit 1; } >&2  # utility routine
+
+parse-args() {
+    # Process optional args
+    #
+    # -h: help
+    # -b: make a branch
+    # -f: full repo. remote and two clones, by different users
+    #     implies '-b'
+	# bash lacks good arg parsing
+    usage="git scratch [-h | -b | -f ]"
+    while getopts ":hbf" opt; do
+        case $opt in          
+            h) echo "$usage" ; exit 0 ;;
+            b) branched=1; shift;;
+            f) remoted=1; branched=1; shift;;
+            \?) echo "Invalid option: -$OPTARG" >&2; die "$usage" ;;
+        esac
+    done
+    if [ $# -ne 0 ]; then
+        die "usage: $usage"
+    fi
 }
 
-# error out
-die() { echo "$@" >&2; exit 1; }
-
-make_basic_repo() {
-  git init --quiet
-  touch .gitkeep
-  if [ "$fixed" ]; then
-    git config user.name root
-    git config user.email root@localhost.localdomain
-  fi
-  git add .
-  git commit -m "Initial commit"
-  git tag initial
+cleanup-old-locals() {
+    # Clean out pre-existing experiments
+    #
+    # "Cleanliness is next to godliness, step 1"
+    for local_repo in $SCRATCH $ITCHY $SCRATCHY; do
+        rm -rf $local_repo                    # remove it
+        if [ -e $local_repo ]; then           # make sure it's gone
+            die "can't remove $local_repo"
+        fi
+    done
 }
 
-parse_args() {
-  # now that we have a couple of args, let's parse with getopts
+cleanup-old-remote() {
+    # Clean out pre-existing "remote"
+    #
+    # "Cleanliness is next to godliness, step 2"
+    # - Remove the "remote" if it's there
+    # - Make sure any required parent directories exist
+    remote_repo=$REMOTE_REPOS_DIRECTORY/scratch.git
+    rm -rf $remote_repo                    # remove it
+    if [ -e $remote_repo ]; then           # make sure it's gone
+        die "cannot remove $remote_repo"
+    fi
+    install -d $REMOTE_REPOS_DIRECTORY || # always succeeds, won't remove pre-existing directories
+        die "cannot create $REMOTE_REPOS_DIRECTORY"
 
-  branched='' conflict='' copy='' fixed='' remoted='' # don't take these from the environment
-  local usage='usage: $0 [-b|-B] [-f] [-r|-R] [dirname]'
-  legal_flags=bBfrR
-
-  while getopts $legal_flags flag; do
-    case $flag in
-      b) branched=yes ;;
-      B) branched=yes conflict=yes ;;
-      f) fixed=yes     # fix times and committers constant at constant values
-         epoch="$(date -u --date='@0')"
-         export GIT_AUTHOR_DATE="$epoch"
-         export GIT_COMMITTER_DATE="$epoch"
-         ;;
-      r) remoted=yes  copy=yes ;;
-      R) remoted=yes ;;
-      # ?) die $usage   ;;
-    esac
-  done
-  shift $(( OPTIND - 1 ));
-
-  dir=${1:-scratch}
 }
 
-parse_args "$@"
+make-scratch() {
+    # Make a minimal scratch repo
+    #
+    # Tagging the very first commit is always a good idea
+    # You can find it with `git checkout $(git rev-list --all --reverse | head -1)`,
+    # but `git checkout initial` is easier to remember. :-)
+    git init --quiet $SCRATCH          # make a scratch directory, under Git version control
+    pushd $SCRATCH > /dev/null         # go there
+    touch .gitkeep                     # a hidden, empty file, to make something to add and commit.
+    git add .gitkeep                   # mark it for commitment,
+    git commit -q -m"Initial commit"   # and commit it!
+    git tag initial                    # tag the first commit
+    popd > /dev/null                   # get back, Jojo
+}
 
-sync=/tmp/$dir.git
-if [ "${GIT_SCRATCH_REMOTE_USERDIRS:-}" ]; then
-  sync=/tmp/$LOGNAME/$dir.git
-fi
-# cleanliness is next to godliness
-rm -rf $dir $sync
-mkdir $dir  # complain if $dir exists but no -f flag
-cd $_
+make-simple-branch() {
+    # Make a simple branching structure
+    #
+    # - one branch
+    # - one commit in each branch
+    # - one conflict: different text on same line in README.md
+    # - ends in master branch
 
-make_basic_repo
+    pushd $SCRATCH > /dev/null                                          # go there
+    branchname=davidian                                                 # q.v.
+    git checkout --quiet -b $branchname                                 # make a new branch
+    echo "# Scratch branch $branchname for exploring Git" > README.md   # give it a README
+    git add .                                                           # add "everything new/changed"
+    git commit -q -m"Add README.md for branch $branchname"              # descriptive commit message
+    git checkout --quiet -                                                # checkout the previous branch
+    echo "# Scratch repo for exploring Git" > README.md                    # README for master branch
+    git add .                                                           # add "everything new/changed"
+    git commit -q -m"Add README.md"                                     # another descriptive message
+    popd > /dev/null                                                    # get back, Jojo
+}
 
-# special sauce
-if [[ "$branched" ]]; then  # make the branches
-  git branch davidian
-  checkout-and-mark davidian
-  checkout-and-mark master  # end up in master
-fi
+make-remote-repo() {
+    # Initialize remote repo from local, then remove local
+    #
+    # - remove old remote before making a new one,
+    # - create a new remote from a local
+    # - cleanup all locals
+    # order is important here.
+    # N.B.: this assumes the remote repo is really created on localhost
 
-if [[ "$remoted" ]]; then   # make a remote
-  cd ..
-  git clone --bare --no-hardlinks $dir $sync
+    cleanup-old-remote
+    git clone --quiet --bare $SCRATCH $REMOTE_REPOS_DIRECTORY/scratch.git  # assumes localhost
+    cleanup-old-locals
+}
 
-  rm -rf $dir itchy scratchy        # remove the original
-
-  if [[ ! "$copy" ]]; then           # a single clone of the remote
-    git clone ssh://localhost$sync 
-  else                               # a pair of clones
-    for i in itchy scratchy; do
-      git clone ssh://localhost$sync $i
-      git -C $i config user.email "$i@localhost"
+make-local-clones() {
+    # Make a pair of local clones of remote
+    #
+    # Each clone will be owned by a different user,
+    # so logs reflect committers.
+    # N.B.: `ssh localhost` must succeed for the clone to work.
+    # To set ssh up on a Mac, search for "remote login" in System Settings
+    for user in itchy scratchy; do
+        local_repo=$TMPDIR/${user}
+        git clone --quiet $remote_repo $local_repo
+        git -C $local_repo config user.email "$user@localhost"
     done
     git -C itchy config user.name "Itchy Mouse"
     git -C scratchy config user.name "Scratchy Cat"
-  fi
+}
+
+parse-args "$@"
+starding_dir=$PWD    # lest we forget
+cleanup-old-locals
+make-scratch
+
+if [ "${branched:-}" ]; then
+    make-simple-branch
 fi
+if ! [ "${remoted:-}" ]; then  # we're done!
+    exit 0
+fi
+
+# making full remote and local clones
+make-remote-repo
+make-local-clones
